name:                hmt
version:             0.1.0.0
github:              "rolfschr/hmt"
license:             BSD3
author:              "Rolf Schröder"
maintainer:          "rolf.schr@gmail.com"
copyright:           "2018 Rolf Schröder"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rolfschr/hmt#readme>

dependencies:
- base >= 4.7 && < 5
- split
- process
- hspec

library:
  source-dirs: src

executables:
  hmt-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hmt

tests:
  hmt-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hmt
